export type FlowStatus = "current" | "historical";

export type FlowStep = {
  id: string;
  kind: "operator" | "inline" | "external";
  label?: string;
};

export type OperatorFlow = {
  description: string;
  fieldMappings: string[];
  id: string;
  inputFields: string[];
  lastUsedAt: string;
  name: string;
  outputFields: string[];
  serviceDomain: string;
  status: FlowStatus;
  steps: FlowStep[];
};

export const operatorFlows: OperatorFlow[] = [
  {
    id: "flow.multimodal-content-review",
    name: "多模态内容理解与质检",
    status: "current",
    serviceDomain: "内容安全",
    lastUsedAt: "2026-07-21",
    description: "把可访问的媒体地址交给模型生成结构化描述，再汇总为质检结果。",
    inputFields: ["urls"],
    outputFields: ["deepseek_output", "quality_result"],
    fieldMappings: ["signed_urls → urls", "deepseek_output → model_result"],
    steps: [
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "quality-schema", kind: "inline", label: "结构校验" },
      { id: "jsonl.agg", kind: "operator" },
    ],
  },
  {
    id: "flow.commerce-caption-governance",
    name: "商品素材描述治理",
    status: "current",
    serviceDomain: "电商内容",
    lastUsedAt: "2026-07-21",
    description: "批量读取商品素材，为每组地址生成结构化描述并汇总交付。",
    inputFields: ["tos_dir"],
    outputFields: ["deepseek_output", "merge_tos_path"],
    fieldMappings: ["signed_urls → urls", "deepseek_output → model_result"],
    steps: [
      { id: "tos.list", kind: "operator" },
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "jsonl.agg", kind: "operator" },
    ],
  },
  {
    id: "flow.short-video-risk-audit",
    name: "短视频风险语义审核",
    status: "current",
    serviceDomain: "短视频治理",
    lastUsedAt: "2026-07-20",
    description: "生成视频语义结果，按审核表达式过滤后汇总问题记录。",
    inputFields: ["urls"],
    outputFields: ["deepseek_output", "risk_result"],
    fieldMappings: ["signed_urls → urls", "deepseek_output → model_result"],
    steps: [
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "eval.filter", kind: "operator" },
      { id: "jsonl.agg", kind: "operator" },
    ],
  },
  {
    id: "flow.ad-creative-structure-check",
    name: "广告创意结构校验",
    status: "current",
    serviceDomain: "广告创意",
    lastUsedAt: "2026-07-20",
    description: "理解广告素材内容，校验返回结构并合并为交付文件。",
    inputFields: ["urls"],
    outputFields: ["deepseek_output", "merge_tos_path"],
    fieldMappings: ["signed_urls → urls", "deepseek_output → model_result"],
    steps: [
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "expr.check", kind: "operator" },
      { id: "csv.merge", kind: "operator" },
    ],
  },
  {
    id: "flow.training-dataset-caption-qc",
    name: "训练集描述质检",
    status: "current",
    serviceDomain: "训练数据",
    lastUsedAt: "2026-07-19",
    description: "展开训练集记录，签名媒体地址并生成可校验的模型描述。",
    inputFields: ["tos_path"],
    outputFields: ["deepseek_output", "merge_tos_path"],
    fieldMappings: ["signed_urls → urls", "deepseek_output → model_result"],
    steps: [
      { id: "csv.expand", kind: "operator" },
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "jsonl.agg", kind: "operator" },
    ],
  },
  {
    id: "flow.copyright-evidence-summary",
    name: "版权证据摘要",
    status: "current",
    serviceDomain: "版权治理",
    lastUsedAt: "2026-07-18",
    description: "对证据素材生成结构化摘要，并汇总为可复核记录。",
    inputFields: ["urls"],
    outputFields: ["deepseek_output", "evidence_summary"],
    fieldMappings: ["signed_urls → urls", "deepseek_output → evidence_summary"],
    steps: [
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "evidence-schema", kind: "inline", label: "证据结构" },
      { id: "jsonl.agg", kind: "operator" },
    ],
  },
  {
    id: "flow.knowledge-asset-media-summary",
    name: "知识资产媒体摘要",
    status: "current",
    serviceDomain: "知识资产",
    lastUsedAt: "2026-07-18",
    description: "读取知识资产目录，生成媒体摘要并合并为入库文件。",
    inputFields: ["tos_dir"],
    outputFields: ["deepseek_output", "merge_tos_path"],
    fieldMappings: ["signed_urls → urls", "deepseek_output → summary"],
    steps: [
      { id: "tos.list", kind: "operator" },
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "csv.merge", kind: "operator" },
    ],
  },
  {
    id: "flow.local-life-media-tagging",
    name: "本地生活素材理解",
    status: "current",
    serviceDomain: "本地生活",
    lastUsedAt: "2026-07-17",
    description: "为门店媒体生成结构化理解结果，并聚合为审核清单。",
    inputFields: ["urls"],
    outputFields: ["deepseek_output", "tag_result"],
    fieldMappings: ["signed_urls → urls", "deepseek_output → tag_result"],
    steps: [
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "jsonl.agg", kind: "operator" },
    ],
  },
  {
    id: "flow.support-attachment-understanding",
    name: "客服附件理解与回写",
    status: "current",
    serviceDomain: "智能客服",
    lastUsedAt: "2026-07-16",
    description: "理解工单附件内容，生成主键后将结构化结果回写数据集。",
    inputFields: ["urls", "tos_path"],
    outputFields: ["deepseek_output", "rowkey"],
    fieldMappings: ["signed_urls → urls", "deepseek_output → model_result"],
    steps: [
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "rowkey", kind: "operator" },
      { id: "hbase.set.v2", kind: "operator" },
    ],
  },
  {
    id: "flow.video-cover-copy-audit",
    name: "视频封面文案审核",
    status: "current",
    serviceDomain: "短视频治理",
    lastUsedAt: "2026-07-15",
    description: "压缩封面后生成内容判断，再按审核条件筛出问题素材。",
    inputFields: ["tos_path"],
    outputFields: ["deepseek_output", "audit_result"],
    fieldMappings: ["image_resize_tos_path → urls", "deepseek_output → model_result"],
    steps: [
      { id: "image.resize", kind: "operator" },
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "eval.filter", kind: "operator" },
    ],
  },
  {
    id: "flow.brand-asset-dedup-review",
    name: "品牌素材重复性复核",
    status: "current",
    serviceDomain: "广告创意",
    lastUsedAt: "2026-07-14",
    description: "展开品牌素材，生成语义结果后对交付记录去重。",
    inputFields: ["tos_path"],
    outputFields: ["deepseek_output", "unique_result"],
    fieldMappings: ["signed_urls → urls", "deepseek_output → model_result"],
    steps: [
      { id: "csv.expand", kind: "operator" },
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "csv.unique", kind: "operator" },
    ],
  },
  {
    id: "flow.catalog-description-normalize",
    name: "商品描述标准化",
    status: "current",
    serviceDomain: "电商内容",
    lastUsedAt: "2026-07-13",
    description: "生成商品描述，校验必需字段并合并为标准交付。",
    inputFields: ["urls"],
    outputFields: ["deepseek_output", "merge_tos_path"],
    fieldMappings: ["signed_urls → urls", "deepseek_output → description"],
    steps: [
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "expr.check", kind: "operator" },
      { id: "csv.merge", kind: "operator" },
    ],
  },
  {
    id: "history.general-model-label-v1",
    name: "通用模型批量标注（旧版）",
    status: "historical",
    serviceDomain: "训练数据",
    lastUsedAt: "2026-05-14",
    description: "曾用于批量读取媒体列表并生成模型标签，当前未注册。",
    inputFields: ["tos_dir"],
    outputFields: ["merge_tos_path"],
    fieldMappings: ["signed_urls → urls"],
    steps: [
      { id: "tos.list", kind: "operator" },
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "csv.merge", kind: "operator" },
    ],
  },
  {
    id: "history.commerce-image-copy-v1",
    name: "商品图文案生成（旧版）",
    status: "historical",
    serviceDomain: "电商内容",
    lastUsedAt: "2026-04-28",
    description: "曾为商品图片生成描述并合并交付，当前未注册。",
    inputFields: ["urls"],
    outputFields: ["deepseek_output", "merge_tos_path"],
    fieldMappings: ["signed_urls → urls", "deepseek_output → copy"],
    steps: [
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "csv.merge", kind: "operator" },
    ],
  },
  {
    id: "history.short-video-topic-v1",
    name: "短视频主题识别（旧版）",
    status: "historical",
    serviceDomain: "短视频治理",
    lastUsedAt: "2026-04-07",
    description: "曾生成短视频主题结果并聚合，当前未注册。",
    inputFields: ["urls"],
    outputFields: ["deepseek_output", "topic_result"],
    fieldMappings: ["signed_urls → urls", "deepseek_output → topic"],
    steps: [
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "jsonl.agg", kind: "operator" },
    ],
  },
  {
    id: "history.ad-copy-risk-v1",
    name: "广告文案风险筛选（旧版）",
    status: "historical",
    serviceDomain: "广告创意",
    lastUsedAt: "2026-03-20",
    description: "曾生成广告文案判断并过滤风险记录，当前未注册。",
    inputFields: ["urls"],
    outputFields: ["deepseek_output", "risk_result"],
    fieldMappings: ["signed_urls → urls", "deepseek_output → model_result"],
    steps: [
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "eval.filter", kind: "operator" },
    ],
  },
  {
    id: "history.copyright-frame-review-v1",
    name: "版权抽帧复核（旧版）",
    status: "historical",
    serviceDomain: "版权治理",
    lastUsedAt: "2026-03-02",
    description: "曾抽取视频帧并生成版权证据摘要，当前未注册。",
    inputFields: ["tos_path"],
    outputFields: ["deepseek_output", "evidence_result"],
    fieldMappings: ["signed_urls → urls", "deepseek_output → evidence"],
    steps: [
      { id: "vod.frame.extract", kind: "operator" },
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "jsonl.agg", kind: "operator" },
    ],
  },
  {
    id: "history.knowledge-media-summary-v1",
    name: "知识媒体摘要（旧版）",
    status: "historical",
    serviceDomain: "知识资产",
    lastUsedAt: "2026-02-18",
    description: "曾读取知识素材并生成摘要文件，当前未注册。",
    inputFields: ["tos_dir"],
    outputFields: ["deepseek_output", "merge_tos_path"],
    fieldMappings: ["signed_urls → urls", "deepseek_output → summary"],
    steps: [
      { id: "tos.list", kind: "operator" },
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "csv.merge", kind: "operator" },
    ],
  },
  {
    id: "history.support-attachment-route-v1",
    name: "客服附件分流（旧版）",
    status: "historical",
    serviceDomain: "智能客服",
    lastUsedAt: "2026-02-06",
    description: "曾理解客服附件并按表达式分流，当前未注册。",
    inputFields: ["urls"],
    outputFields: ["deepseek_output", "route_result"],
    fieldMappings: ["signed_urls → urls", "deepseek_output → model_result"],
    steps: [
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "expr.check", kind: "operator" },
    ],
  },
  {
    id: "history.local-life-photo-tags-v1",
    name: "门店图片标签（旧版）",
    status: "historical",
    serviceDomain: "本地生活",
    lastUsedAt: "2026-01-22",
    description: "曾为门店图片生成标签并汇总，当前未注册。",
    inputFields: ["urls"],
    outputFields: ["deepseek_output", "tag_result"],
    fieldMappings: ["signed_urls → urls", "deepseek_output → tags"],
    steps: [
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "jsonl.agg", kind: "operator" },
    ],
  },
  {
    id: "history.training-caption-v2",
    name: "训练集描述生成 V2（旧版）",
    status: "historical",
    serviceDomain: "训练数据",
    lastUsedAt: "2025-12-19",
    description: "曾展开训练记录并生成描述汇总，当前未注册。",
    inputFields: ["tos_path"],
    outputFields: ["deepseek_output", "merge_tos_path"],
    fieldMappings: ["signed_urls → urls", "deepseek_output → caption"],
    steps: [
      { id: "csv.expand", kind: "operator" },
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "jsonl.agg", kind: "operator" },
    ],
  },
  {
    id: "history.brand-image-understanding-v1",
    name: "品牌图片理解（旧版）",
    status: "historical",
    serviceDomain: "广告创意",
    lastUsedAt: "2025-11-28",
    description: "曾压缩品牌图片并生成描述交付，当前未注册。",
    inputFields: ["tos_path"],
    outputFields: ["deepseek_output", "merge_tos_path"],
    fieldMappings: ["signed_urls → urls", "deepseek_output → summary"],
    steps: [
      { id: "image.resize", kind: "operator" },
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "csv.merge", kind: "operator" },
    ],
  },
  {
    id: "history.catalog-audit-v1",
    name: "商品目录审核（旧版）",
    status: "historical",
    serviceDomain: "电商内容",
    lastUsedAt: "2025-10-16",
    description: "曾生成商品目录判断并筛出异常记录，当前未注册。",
    inputFields: ["urls"],
    outputFields: ["deepseek_output", "audit_result"],
    fieldMappings: ["signed_urls → urls", "deepseek_output → model_result"],
    steps: [
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "eval.filter", kind: "operator" },
    ],
  },
  {
    id: "history.video-cover-review-v1",
    name: "视频封面理解（旧版）",
    status: "historical",
    serviceDomain: "短视频治理",
    lastUsedAt: "2025-09-30",
    description: "曾抽取视频帧并生成封面理解结果，当前未注册。",
    inputFields: ["tos_path"],
    outputFields: ["deepseek_output", "review_result"],
    fieldMappings: ["signed_urls → urls", "deepseek_output → model_result"],
    steps: [
      { id: "vod.frame.extract", kind: "operator" },
      { id: "tos.sign", kind: "operator" },
      { id: "ai-platform.deepseek", kind: "operator" },
      { id: "jsonl.agg", kind: "operator" },
    ],
  },
  {
    id: "flow.video-segment-review",
    name: "视频片段理解与人工复核",
    status: "current",
    serviceDomain: "短视频治理",
    lastUsedAt: "2026-07-20",
    description: "将长视频切成片段，逐段生成描述，并交给人工复核。",
    inputFields: ["tos_path"],
    outputFields: ["segment_caption", "review_result"],
    fieldMappings: ["split_tos_path → tos_path"],
    steps: [
      { id: "vod.split", kind: "operator" },
      { id: "csv.expand", kind: "operator" },
      { id: "ai-platform.gemini", kind: "operator" },
      { id: "human-review", kind: "external", label: "人工复核" },
    ],
  },
  {
    id: "flow.vod-preview-delivery",
    name: "VOD 预览交付",
    status: "current",
    serviceDomain: "内容交付",
    lastUsedAt: "2026-07-21",
    description: "上传媒体、完成转码并取回可供验收的预览地址。",
    inputFields: ["tos_path"],
    outputFields: ["preview_url"],
    fieldMappings: ["vid → vid", "runid → runid"],
    steps: [
      { id: "vod.upload", kind: "operator" },
      { id: "vod.transcoding.start", kind: "operator" },
      { id: "vod.transcoding.query.v2", kind: "operator" },
      { id: "vod.transcoding.get", kind: "operator" },
    ],
  },
  {
    id: "flow.audio-transcription",
    name: "音频转写入库",
    status: "current",
    serviceDomain: "语音语料",
    lastUsedAt: "2026-07-19",
    description: "提交音频转写任务，查询文本结果并写入数据集。",
    inputFields: ["audio_tos_path", "rowkey"],
    outputFields: ["asr"],
    fieldMappings: ["asr_task_id → asr_task_id", "asr → transcript"],
    steps: [
      { id: "vod.audio.asr.submit", kind: "operator" },
      { id: "vod.audio.asr.query", kind: "operator" },
      { id: "hbase.set.v2", kind: "operator" },
    ],
  },
  {
    id: "flow.image-quality-gate",
    name: "图片质量筛选与汇总",
    status: "current",
    serviceDomain: "训练数据",
    lastUsedAt: "2026-07-18",
    description: "统一图片尺寸，补充质量分，再将通过的数据汇总交付。",
    inputFields: ["tos_path"],
    outputFields: ["merge_tos_path"],
    fieldMappings: ["resize_tos_path → tos_path", "average_ap_score → score"],
    steps: [
      { id: "image.resize", kind: "operator" },
      { id: "cn_clip.artimuse", kind: "operator" },
      { id: "ap_v25.filter", kind: "operator" },
      { id: "csv.merge", kind: "operator" },
    ],
  },
  {
    id: "history.black-border-cleanup-v1",
    name: "视频黑边清理（旧版）",
    status: "historical",
    serviceDomain: "视频加工",
    lastUsedAt: "2026-01-12",
    description: "曾先检测黑边参数再执行裁剪，当前未注册。",
    inputFields: ["tos_path"],
    outputFields: ["crop_tos_path"],
    fieldMappings: ["black_border_crop → crop_config"],
    steps: [
      { id: "vod.crop.blackborder.get", kind: "operator" },
      { id: "vod.crop.blackborder.crop", kind: "operator" },
      { id: "vod.upload.tos", kind: "operator" },
    ],
  },
  {
    id: "history.dataset-write-v1",
    name: "数据集字段回写（旧版）",
    status: "historical",
    serviceDomain: "数据治理",
    lastUsedAt: "2025-12-08",
    description: "曾根据对象路径生成主键并回写字段，当前未注册。",
    inputFields: ["tos_path"],
    outputFields: ["rowkey"],
    fieldMappings: ["rowkey → rowkey"],
    steps: [
      { id: "rowkey", kind: "operator" },
      { id: "hbase.get", kind: "operator" },
      { id: "hbase.set", kind: "operator" },
    ],
  },
];
