#!/usr/bin/env python3
"""Build a source-free Handler catalog from an exported operator TypeScript file."""

from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = PROJECT_ROOT / "src" / "lib" / "handler-data.ts"
ARRAY_MARKER = "export const operatorRecords: OperatorRecord[] = "


def read_records(path: Path) -> list[dict[str, object]]:
    source = path.read_text("utf-8")
    start = source.find(ARRAY_MARKER)
    if start == -1:
        raise ValueError(f"operatorRecords array not found in {path}")
    array_start = source.find("[", start + len(ARRAY_MARKER))
    array_end = source.rfind("];")
    if array_start == -1 or array_end == -1 or array_end < array_start:
        raise ValueError(f"operatorRecords array is incomplete in {path}")
    records = json.loads(source[array_start : array_end + 1])
    if not isinstance(records, list):
        raise ValueError("operatorRecords must be an array")
    return records


def sanitize_markdown(value: str) -> str:
    evidence_marker = "\n## 证据"
    return value.split(evidence_marker, 1)[0].strip()


def convert(record: dict[str, object]) -> dict[str, object]:
    return {
        "entityType": "handler",
        "handlerId": record["id"],
        "displayName": record["displayName"],
        "initial": record["initial"],
        "domains": record["domains"],
        "behavior": record["behavior"],
        "cardinality": record["cardinality"],
        "intro": record["intro"],
        "status": "enabled",
        "provenanceStatus": "verified",
        "testability": "unknown",
        "costProfile": {
            "costValue": None,
            "costUnit": "次",
            "currency": "CNY",
            "isPlaceholder": True,
            "sourceStatus": "placeholder",
        },
        "resourceProfile": {
            "resourceId": None,
            "usageValue": None,
            "usageUnit": "路并发",
            "isPlaceholder": True,
            "sourceStatus": "placeholder",
        },
        "detailMarkdown": sanitize_markdown(str(record["wiki"])),
    }


def render(records: list[dict[str, object]]) -> str:
    serialized = json.dumps(records, ensure_ascii=False, indent=2)
    return (
        "/* Generated by scripts/build_public_handler_data.py. Do not hand-edit. */\n\n"
        'import type { HandlerRecord } from "@/lib/catalog-types";\n\n'
        f"export const handlerRecords: HandlerRecord[] = {serialized};\n"
    )


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(prefix=path.name, dir=path.parent)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as temporary:
            temporary.write(content)
        Path(temporary_name).replace(path)
    except Exception:
        Path(temporary_name).unlink(missing_ok=True)
        raise


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    records = [convert(record) for record in read_records(args.source)]
    ids = [str(record["handlerId"]) for record in records]
    duplicates = sorted({handler_id for handler_id in ids if ids.count(handler_id) > 1})
    if duplicates:
        raise SystemExit("duplicate Handler IDs: " + ", ".join(duplicates))

    atomic_write(args.output.resolve(), render(records))
    print(json.dumps({"handlers": len(records), "output": str(args.output.resolve())}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError) as error:
        print(json.dumps({"error": str(error)}, ensure_ascii=False), file=sys.stderr)
        raise SystemExit(1)
